### ISSUE TITLE
VBridger has issues connecting to IPhone

### ISSUE THREAD

**Issue by Zoinks32** [PiPuProductions/VBridger-Documentation#2]
I was attempting to connect VBridger to VTubeStudio, and i had the network on Public, with the firewall exception for VtubeStudio. It said it connected fine to VtubeStudio, but upon trying to move with the tracking from my iphone it wouldn't work. The Model would just stand still. If pictures are needed i'll provide.

**Comment by PiPuProductions** [comment]
Hello!

Please join our discord via the VBridger menu to access our help section~
There is an FAQ for common problems as well as a thread where you can directly ask for help should the FAQ fail to help you!
